name = "aoc-2024"
version = "0.1.0"
defaultTargets = ["aoc-2024"]

[[require]]
name = "Cli"
git = "https://github.com/leanprover/lean4-cli.git"
rev = "main"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "main"

[[lean_lib]]
name = "Aoc2024"

[[lean_exe]]
name = "aoc-2024"
root = "Main"

[[lean_exe]]
name = "day01"
root = "Aoc2024.Day01"

[[lean_exe]]
name = "day02"
root = "Aoc2024.Day02"

[[lean_exe]]
name = "day03"
root = "Aoc2024.Day03"

[[lean_exe]]
name = "day04"
root = "Aoc2024.Day04"

[[lean_exe]]
name = "day05"
root = "Aoc2024.Day05"

[[lean_exe]]
name = "day06"
root = "Aoc2024.Day06"

[[lean_exe]]
name = "day07"
root = "Aoc2024.Day07"

[[lean_exe]]
name = "day08"
root = "Aoc2024.Day08"

[[lean_exe]]
name = "day09"
root = "Aoc2024.Day09"

[[lean_exe]]
name = "day10"
root = "Aoc2024.Day10"

[[lean_exe]]
name = "day11"
root = "Aoc2024.Day11"

[[lean_exe]]
name = "day12"
root = "Aoc2024.Day12"

[[lean_exe]]
name = "day13"
root = "Aoc2024.Day13"

[[lean_exe]]
name = "day14"
root = "Aoc2024.Day14"

[[lean_exe]]
name = "day15"
root = "Aoc2024.Day15"

[[lean_exe]]
name = "day16"
root = "Aoc2024.Day16"

[[lean_exe]]
name = "day17"
root = "Aoc2024.Day17"

[[lean_exe]]
name = "day18"
root = "Aoc2024.Day18"

[[lean_exe]]
name = "day19"
root = "Aoc2024.Day19"

[[lean_exe]]
name = "day20"
root = "Aoc2024.Day20"
