name = "aoc-2024"
version = "0.1.0"
defaultTargets = ["aoc-2024"]

[[require]]
name = "Cli"
git = "https://github.com/leanprover/lean4-cli.git"
rev = "main"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "main"

[[lean_lib]]
name = "Aoc2024"

[[lean_exe]]
name = "aoc-2024"
root = "Main"

[[lean_exe]]
name = "day01"
root = "Aoc2024.Day01"

[[lean_exe]]
name = "day02"
root = "Aoc2024.Day02"

[[lean_exe]]
name = "day03"
root = "Aoc2024.Day03"

[[lean_exe]]
name = "day04"
root = "Aoc2024.Day04"

[[lean_exe]]
name = "day05"
root = "Aoc2024.Day05"

[[lean_exe]]
name = "day06"
root = "Aoc2024.Day06"
